---
title: "CEAS CFAs"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(feather)
library(psych)
library(lavaan)
library(blavaan)
library(bayesplot)
library(loo)
library(semPlot)
future::plan("multisession")
source("funcs.R")
library(knitr)
```

### CEAS-SC

```{r}
ceas_sc <- read_feather("../results/tidy_ceas_sc.feather")
```

```{r}
ceas_sc_wide <- ceas_sc %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.)))

ceas_sc_wide
```

```{r}
ceas_sc_cor <- round(cor(ceas_sc_wide %>% select(-ResponseId), method="spearman"), 2)
kable(ceas_sc_cor)
```

```{r}
eigen(ceas_sc_cor)$values
```

```{r}
scale_name <- "CEAS-SC"
df <- ceas_sc_wide
```

## One Factor

```{r}
model_name <- "One Factor"
model_string <- "CEAS_SC =~ CEAS_SC1_1 + CEAS_SC1_2 + CEAS_SC1_4 + CEAS_SC1_5 + CEAS_SC1_6 + CEAS_SC1_8 + CEAS_SC2_1 + CEAS_SC2_2 + CEAS_SC2_4 + CEAS_SC2_5"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

### CEAS-SC Two Factor

```{r}
model_name <- "Two Factor"
model_string <- "
CEAS_SC_Engagement =~ CEAS_SC1_1 + CEAS_SC1_2 + CEAS_SC1_4 + CEAS_SC1_5 + CEAS_SC1_6 + CEAS_SC1_8
CEAS_SC_Action =~ CEAS_SC2_1 + CEAS_SC2_2 + CEAS_SC2_4 + CEAS_SC2_5
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

### CEAS-SC Level One Model

```{r}
model_name <- "Level One"
model_string <- "
CEAS_SC_Engagement =~ CEAS_SC1_1 + CEAS_SC1_2 + CEAS_SC1_4 + CEAS_SC1_5 + CEAS_SC1_6 + CEAS_SC1_8
CEAS_SC_Action =~ CEAS_SC2_1 + CEAS_SC2_2 + CEAS_SC2_4 + CEAS_SC2_5
CEAS_SC =~ CEAS_SC_Engagement + CEAS_SC_Action
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

### Three factor

```{r}
model_name <- "Three Factor"
model_string <- "
CEAS_SC_Engagement_1 =~ CEAS_SC1_2 + CEAS_SC1_4
CEAS_SC_Engagement_2 =~ CEAS_SC1_1 + CEAS_SC1_5 + CEAS_SC1_6 + CEAS_SC1_8
CEAS_SC_Action =~ CEAS_SC2_1 + CEAS_SC2_2 + CEAS_SC2_4 + CEAS_SC2_5
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

### Level Two Model (Equal Loadings)

```{r}
model_name <- "Third Order (Equal Loadings)"
model_string <- "
CEAS_SC_Engagement_1 =~ CEAS_SC1_2 + CEAS_SC1_4
CEAS_SC_Engagement_2 =~ CEAS_SC1_1 + CEAS_SC1_5 + CEAS_SC1_6 + CEAS_SC1_8
CEAS_SC_Engagement =~ 1*CEAS_SC_Engagement_1 + 1*CEAS_SC_Engagement_2
CEAS_SC_Action =~ CEAS_SC2_1 + CEAS_SC2_2 + CEAS_SC2_4 + CEAS_SC2_5
CEAS_SC =~ 1*CEAS_SC_Engagement + 1*CEAS_SC_Action
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

### Omega

```{r}
model_string <- "
CEAS_SC_Engagement_1 =~ CEAS_SC1_2 + CEAS_SC1_4
CEAS_SC_Engagement_2 =~ CEAS_SC1_1 + CEAS_SC1_5 + CEAS_SC1_6 + CEAS_SC1_8
CEAS_SC_Engagement =~ CEAS_SC_Engagement_1 + CEAS_SC_Engagement_2
CEAS_SC_Action =~ CEAS_SC2_1 + CEAS_SC2_2 + CEAS_SC2_4 + CEAS_SC2_5
CEAS_SC =~ CEAS_SC_Engagement + CEAS_SC_Action
"
```

```{r}
get_omegas(fit_cfa(model_string, df))
```

### CEAS-FROM

```{r}
ceas_from <- read_feather("../results/tidy_ceas_from.feather")
```

```{r}
ceas_from_wide <- ceas_from %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.)))
```

```{r}
ceas_from_cor <- cor(ceas_from_wide %>% select(-ResponseId), method="spearman")
ceas_from_cor
```

```{r}
eigen(ceas_from_cor)$values
```

```{r}
scale_name <- "CEAS-FROM"
df <- ceas_from_wide
```

### One Factor

```{r}
model_name <- "One Factor"
model_string <- "CEAS_FROM =~ CEAS_FROM1_1 + CEAS_FROM1_2 + CEAS_FROM1_4 + CEAS_FROM1_5 + CEAS_FROM1_6 + CEAS_FROM1_8 + CEAS_FROM2_1 + CEAS_FROM2_2 + CEAS_FROM2_4 + CEAS_FROM2_5
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

### Two Factor

```{r}
model_name <- "Two Factor"
model_string <- "
CEAS_FROM_Engagement =~ CEAS_FROM1_1 + CEAS_FROM1_2 + CEAS_FROM1_4 + CEAS_FROM1_5 + CEAS_FROM1_6 + CEAS_FROM1_8
CEAS_FROM_Action =~ CEAS_FROM2_1 + CEAS_FROM2_2 + CEAS_FROM2_4 + CEAS_FROM2_5
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

### Second Order

```{r}
model_name <- "Second Order"
model_string <- "
CEAS_FROM_Engagement =~ CEAS_FROM1_1 + CEAS_FROM1_2 + CEAS_FROM1_4 + CEAS_FROM1_5 + CEAS_FROM1_6 + CEAS_FROM1_8
CEAS_FROM_Action =~ CEAS_FROM2_1 + CEAS_FROM2_2 + CEAS_FROM2_4 + CEAS_FROM2_5
CEAS_FROM =~ CEAS_FROM_Engagement + CEAS_FROM_Action
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
get_omegas(cfa_fit)
```

### CEAS-TO

```{r}
ceas_to <- read_feather("../results/tidy_ceas_to.feather")
```

```{r}
ceas_to_wide <- ceas_to %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.)))
```

```{r}
ceas_to_cor <- cor(ceas_to_wide %>% select(-ResponseId), method="spearman")
ceas_to_cor
```

```{r}
eigen(ceas_to_cor)$values
```

```{r}
df <- ceas_to_wide
scale_name <- "CEAS-TO"
```

### One Factor

```{r}
model_name <- "One Factor"
model_string <- "CEAS_TO =~ CEAS_TO1_1 + CEAS_TO1_2 + CEAS_TO1_4 + CEAS_TO1_5 + CEAS_TO1_6 + CEAS_TO1_8 + CEAS_TO2_1 + CEAS_TO2_2 + CEAS_TO2_4 + CEAS_TO2_5
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

### Two Factor

```{r}
model_name <- "Two Factor"
model_string <- "
CEAS_TO_Engagement =~ CEAS_TO1_1 + CEAS_TO1_2 + CEAS_TO1_4 + CEAS_TO1_5 + CEAS_TO1_6 + CEAS_TO1_8
CEAS_TO_Action =~ CEAS_TO2_1 + CEAS_TO2_2 + CEAS_TO2_4 + CEAS_TO2_5
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

### Second Order (Equal Loadings)

```{r}
model_name <- "Second Order (Equal Loadings)"
model_string <- "
CEAS_TO_Engagement =~ CEAS_TO1_1 + CEAS_TO1_2 + CEAS_TO1_4 + CEAS_TO1_5 + CEAS_TO1_6 + CEAS_TO1_8
CEAS_TO_Action =~ CEAS_TO2_1 + CEAS_TO2_2 + CEAS_TO2_4 + CEAS_TO2_5
CEAS_TO =~ 1*CEAS_TO_Engagement + 1*CEAS_TO_Action
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

### Omega

```{r}
model_string <- "
CEAS_TO_Engagement =~ CEAS_TO1_1 + CEAS_TO1_2 + CEAS_TO1_4 + CEAS_TO1_5 + CEAS_TO1_6 + CEAS_TO1_8
CEAS_TO_Action =~ CEAS_TO2_1 + CEAS_TO2_2 + CEAS_TO2_4 + CEAS_TO2_5
CEAS_TO =~ CEAS_TO_Engagement + CEAS_TO_Action
"
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
get_omegas(cfa_fit)
```

```{r}
sessionInfo()
```
