---
title: "SOCS-S Initial CFA"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(feather)
library(lavaan)
library(psych)
library(broom)
library(ggthemes)
library(semTools)
library(ggcorrplot)
library(viridis)
```

```{r}
df <- read_feather("../results/tidy_filtered_responses.feather") %>% 
  mutate(response = ordered(response, levels = c("1", "2", "3", "4", "5")))
df
```




```{r}
socs_s_df <- df %>% 
  mutate(response = as.numeric(response)) %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  select(starts_with("SOCS-S")) %>% 
  rename_with(~str_c("s", str_extract(., "\\d+"))) %>% 
  filter_all(all_vars(!is.na(.))) 

socs_s_df
```

```{r}
socs_s <- polychoric(socs_s_df)
socs_s
```

```{r}
eigen(socs_s$rho)$values
```
Positive semidefinite

## One-factor model

```{r}
one_factor_model <- str_c("compassion =~ ", str_c(colnames(socs_s_df), collapse = " + "))
one_factor_model
```

(How should I deal with non-responses? Possibly use SEM)
(I am going to remove them for now and then use MICE)

```{r}
one_factor_cfa <- cfa(
  one_factor_model, 
  data=socs_s_df, 
  estimator="MLR"
  )
one_factor_cfa
```
```{r}
one_factor_glance <- glance(one_factor_cfa)
one_factor_glance
```

```{r}
five_factor_model <- '
recognizing_suffering =~ s1 + s6 + s11 + s16
universality_of_suffering =~ s2 + s7 + s12 + s17
feeling_of_suffering =~ s3 + s8 + s13 + s18
tolerating_discomfort =~ s4 + s9 + s14 + s19
alleviate_suffering =~ s5 + s10 + s15 + s20
'
```

```{r}
five_factor_cfa <- cfa(
  five_factor_model, 
  data=socs_s_df, 
  estimator="MLR"
  )
five_factor_cfa
```
```{r}
five_factor_glance <- glance(five_factor_cfa)
five_factor_glance
```
```{r}
socs_s_parameter_estimates <- tidy(five_factor_cfa)
socs_s_parameter_estimates
```



```{r}
ggcorrplot(socs_s$rho, ggtheme=theme_few()) +
  scale_fill_viridis()
```

```{r}
ggcorrplot(socs_o$rho, ggtheme=theme_few()) +
  scale_fill_viridis()
```



```{r}
cov2cor(lavInspect(five_factor_cfa, "cov.lv"))
```



```{r}
hierarchical_factor_model <- '
recognizing_suffering =~ s1 + s6 + s11 + s16
universality_of_suffering =~ s2 + s7 + s12 + s17
feeling_of_suffering =~ s3 + s8 + s13 + s18
tolerating_discomfort =~ s4 + s9 + s14 + s19
alleviate_suffering =~ s5 + s10 + s15 + s20
compassion =~ recognizing_suffering + universality_of_suffering + feeling_of_suffering + tolerating_discomfort + alleviate_suffering
'
hierarchical_factor_model
```

```{r}
hierarchical_factor_cfa <- cfa(
  hierarchical_factor_model, 
  data=socs_s_df, 
  estimator="MLR"
  )
hierarchical_factor_cfa
```
```{r}
hierarchical_factor_glance <- glance(hierarchical_factor_cfa)
hierarchical_factor_glance
```

```{r}
bind_rows(
  one_factor_glance,
  five_factor_glance,
  hierarchical_factor_glance
)
```




## Internal Reliability (Total Scale)


```{r}
summary(alpha(socs_s_df))
```

```{r}
summary(omega(socs_s_df))
```



## Ceiling and Floor Effects

```{r}
total_scores <- df %>% 
  mutate(response= as.numeric(response)) %>% 
  group_by(ResponseId) %>% 
  mutate(any_nas = any(is.na(response))) %>% 
  filter(any_nas == FALSE) %>% 
  filter(str_detect(item, "SOCS-S")) %>% 
  summarise(total = sum(response))

total_scores
```

```{r}
ggplot(total_scores, aes(x=total)) +
  geom_histogram() +
  theme_few()
```

```{r}
total_scores %>% 
  filter(total == 100)
```
## SOCS-O

```{r}
socs_o_df <- df %>% 
  filter(str_detect(item, "SOCS-O")) %>% 
  mutate(response = as.numeric(response)) %>% 
  mutate(item_number = if_else(as.numeric(str_extract(item, "\\d+")) > 5, as.numeric(str_extract(item, "\\d+")) - 1, as.numeric(str_extract(item, "\\d+")))) %>% 
  mutate(item = str_c("o", item_number)) %>% 
  select(-item_number) %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  select(-ResponseId) %>% 
  filter_all(all_vars(!is.na(.)))
  
```

```{r}
socs_o_df %>% 
  write_feather("../results/tidy_socs_o.feather")
```



```{r}
socs_o_df
```


```{r}
socs_o <- polychoric(socs_o_df)
socs_o
```
```{r}
ggcorrplot(socs_o$rho, ggtheme=theme_few()) +
  scale_fill_viridis()
```


```{r}
eigen(socs_o$rho)$values
```
```{r}
one_factor_model <- str_c("compassion =~ ", str_c(colnames(socs_o_df), collapse = " + "))
one_factor_model
```

```{r}
one_factor_cfa <- cfa(
  one_factor_model, 
  data=socs_o_df, 
  estimator="MLR"
  )
one_factor_cfa
```

```{r}
one_factor_glance <- glance(one_factor_cfa)
one_factor_glance
```

```{r}
five_factor_model <- '
recognizing_suffering =~ o1 + o6 + o11 + o16
universality_of_suffering =~ o2 + o7 + o12 + o17
feeling_of_suffering =~ o3 + o8 + o13 + o18
tolerating_discomfort =~ o4 + o9 + o14 + o19
alleviate_suffering =~ o5 + o10 + o15 + o20
'
```


```{r}
five_factor_cfa <- cfa(
  five_factor_model, 
  data=socs_o_df, 
  estimator="MLR"
  )
five_factor_cfa
```
```{r}
summary(five_factor_cfa)
```


```{r}
cov2cor(lavInspect(five_factor_cfa, "cov.lv"))
```
```{r}
socs_s_parameter_estimates
```

```{r}
socs_s_parameter_estimates %>% 
  filter(op == "=~") %>% 
  summarise(mean(estimate))
```


```{r}
five_factor_pop_model <- '
recognizing_suffering =~ 1.14*o1 + 1.14*o6 + 1.14*o11 + 1.14*o16
universality_of_suffering =~ 1.14*o2 + 1.14*o7 + 1.14*o12 + 1.14*o17
feeling_of_suffering =~ 1.14*o3 + 1.14*o8 + 1.14*o13 + 1.14*o18
tolerating_discomfort =~ 1.14*o4 + 1.14*o9 + 1.14*o14 + 1.14*o19
alleviate_suffering =~ 1.14*o5 + 1.14*o10 + 1.14*o15 + 1.14*o20

recognizing_suffering ~~ 0.26*recognizing_suffering
universality_of_suffering ~~ 0.26*universality_of_suffering
feeling_of_suffering ~~ 0.26*feeling_of_suffering
tolerating_discomfort ~~ 0.26*tolerating_discomfort
alleviate_suffering ~~ 0.26*alleviate_suffering

recognizing_suffering ~~ 0.26*universality_of_suffering
recognizing_suffering ~~ 0.26*feeling_of_suffering
recognizing_suffering ~~ 0.26*tolerating_discomfort
recognizing_suffering ~~ 0.26*alleviate_suffering

universality_of_suffering ~~ 0.26*feeling_of_suffering
universality_of_suffering ~~ 0.26*tolerating_discomfort
universality_of_suffering ~~ 0.26*alleviate_suffering

feeling_of_suffering ~~ 0.26*tolerating_discomfort
feeling_of_suffering ~~ 0.26*alleviate_suffering

tolerating_discomfort ~~ 0.26*alleviate_suffering
'

```

```{r}
five_factor_pa <- SSpower(five_factor_model, popModel = five_factor_pop_model, n=80, nparam=1, std.lv=TRUE)
```

```{r}
five_factor_pa
```



```{r}
eigen(lavInspect(five_factor_cfa, "cov.lv"))
```
```{r}
lavInspect(five_factor_cfa, "cov.lv")
```


```{r}
inspect(five_factor_cfa,what="std")$lambda
```


```{r}
five_factor_glance <- glance(five_factor_cfa)
five_factor_glance
```

```{r}
hierarchical_factor_model <- '
recognizing_suffering =~ o1 + o6 + o11 + o16
universality_of_suffering =~ o2 + o7 + o12 + o17
feeling_of_suffering =~ o3 + o8 + o13 + o18
tolerating_discomfort =~ o4 + o9 + o14 + o19
alleviate_suffering =~ o5 + o10 + o15 + o20
compassion =~ recognizing_suffering + universality_of_suffering + feeling_of_suffering + tolerating_discomfort + alleviate_suffering
'
hierarchical_factor_model
```

```{r}
hierarchical_factor_cfa <- cfa(
  hierarchical_factor_model, 
  data=socs_o_df, 
  estimator="MLR"
  )
hierarchical_factor_cfa
```


```{r}
sessionInfo()
```

