---
title: "DASS_21 CFAs"
output: html_document
date: "2022-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(feather)
library(psych)
library(effectsize)
source("funcs.R")
```

```{r}
dass <- read_feather("../results/tidy_dass.feather") %>% 
  mutate(item = str_replace(item, "-", "_"))
```

```{r}
dass_wide <- dass %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  select(-ResponseId)
```

```{r, correlation}
dass_corr <- polychoric(dass_wide)
```

```{r fig.asp = 0.8, fig.width = 7}
format_correlation(dass_corr$rho, "DASS-21 Polychoric")
```

```{r}
eigen(dass_corr$rho)$values
```

```{r}
scale_name <- "DASS_21"
df <- dass_wide
```

## One-factor model

```{r}
model_name <- "One Factor"
model_string <- "dass =~ DASS_21_1 + DASS_21_2 + DASS_21_3 + DASS_21_4 + DASS_21_5 + DASS_21_6 + DASS_21_7 + DASS_21_8 + DASS_21_9 + DASS_21_10 + DASS_21_11 + DASS_21_12 + DASS_21_13 + DASS_21_14 + DASS_21_15 + DASS_21_16 + DASS_21_17 + DASS_21_18 + DASS_21_19 + DASS_21_20 + DASS_21_21"
model_string
```

```{r}
cfa_fit <- cfa(
    model_string, 
    data=df,
    estimator="MLR",
    std.lv=TRUE
  )
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
dass_one_fit <- fit_measure
```

### DASS-21 Three Factor

```{r}
model_name <- "Three Factor"
model_string <- "
somatization =~ DASS_21_1 + DASS_21_6 + DASS_21_8 + DASS_21_11 + DASS_21_12 + DASS_21_14 + DASS_21_18
anxiety =~ DASS_21_2 + DASS_21_4 + DASS_21_7 + DASS_21_9 + DASS_21_15 + DASS_21_19 + DASS_21_20
depression =~ DASS_21_3 + DASS_21_5 + DASS_21_10 + DASS_21_13 + DASS_21_16 + DASS_21_17 + DASS_21_21"
model_string
```

```{r}
cfa_fit <- cfa(
    model_string, 
    data=df,
    estimator="MLR",
    std.lv=TRUE
  )
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
dass_three_fit <- fit_measure
```

### Bifactor Model

```{r}
model_name <- "Bifactor"
model_string <- "
somatization =~ DASS_21_1 + DASS_21_6 + DASS_21_8 + DASS_21_11 + DASS_21_12 + DASS_21_14 + DASS_21_18
anxiety =~ DASS_21_2 + DASS_21_4 + DASS_21_7 + DASS_21_9 + DASS_21_15 + DASS_21_19 + DASS_21_20
depression =~ DASS_21_3 + DASS_21_5 + DASS_21_10 + DASS_21_13 + DASS_21_16 + DASS_21_17 + DASS_21_21
dass =~ DASS_21_1 + DASS_21_2 + DASS_21_3 + DASS_21_4 + DASS_21_5 + DASS_21_6 + DASS_21_7 + DASS_21_8 + DASS_21_9 + DASS_21_10 + DASS_21_11 + DASS_21_12 + DASS_21_13 + DASS_21_14 + DASS_21_15 + DASS_21_16 + DASS_21_17 + DASS_21_18 + DASS_21_19 + DASS_21_20 + DASS_21_21
"
model_string
```

```{r}
cfa_fit <- cfa(
    model_string, 
    data=df,
    estimator="MLR",
    std.lv=TRUE
  )
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
dass_three_fit <- fit_measure
```

```{r}
get_omegas(cfa_fit)
```

### Hierarchical Model

```{r}
model_name <- "Hierarchical"
model_string <- "
somatization =~ DASS_21_1 + DASS_21_6 + DASS_21_8 + DASS_21_11 + DASS_21_12 + DASS_21_14 + DASS_21_18
anxiety =~ DASS_21_2 + DASS_21_4 + DASS_21_7 + DASS_21_9 + DASS_21_15 + DASS_21_19 + DASS_21_20
depression =~ DASS_21_3 + DASS_21_5 + DASS_21_10 + DASS_21_13 + DASS_21_16 + DASS_21_17 + DASS_21_21
dass =~ somatization + anxiety + depression
"
model_string
```

```{r}
cfa_fit <- cfa(
    model_string, 
    data=df,
    estimator="MLR",
    std.lv=TRUE,
    bounds=TRUE
  )
```

```{r}
get_omegas(cfa_fit)
```

```{r}
sessionInfo()
```
