---
title: "ECR CFAs"
output:
  word_document: default
  html_document: default
date: "2022-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(feather)
library(psych)
library(effectsize)
source("funcs.R")
```

```{r}
ecr <- read_feather("../results/tidy_ecr.feather") 
  # mutate(item = str_replace(item, "-", "_"))
```

```{r}
ecr_wide <- ecr %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  select(-ResponseId)
```

```{r, correlation}
ecr_corr <- polychoric(ecr_wide)
```

```{r fig.asp = 0.8, fig.width = 7}
format_correlation(ecr_corr$rho, "ECR-12 Polychoric")
```

```{r}
eigen(ecr_corr$rho)$values
```

```{r}
scale_name <- "ECR-12"
df <- ecr_wide
```

## One-factor model

```{r}
model_name <- "One Factor"
model_string <- "ECR =~ ECR_1 + ECR_2 + ECR_3 + ECR_4 + ECR_5 + ECR_6 + ECR_7 + ECR_8 + ECR_9 + ECR_10 + ECR_11 + ECR_12"
model_string
```

```{r}
cfa_fit <- cfa(
    model_string, 
    data=df,
    estimator="MLR",
    std.lv=TRUE
  )
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
ecr_one_fit <- fit_measure
```

## Two Factor

```{r}
model_name <- "Two Factor"
model_string <- "
Anxiety =~ ECR_1 + ECR_2 + ECR_3 + ECR_5 + ECR_7 + ECR_8
Avoidance =~ ECR_4 + ECR_6 + ECR_9 + ECR_10 + ECR_11 + ECR_12
"
model_string
```

```{r}
cfa_fit <- cfa(
    model_string, 
    data=df,
    estimator="MLR",
    std.lv=TRUE
  )
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
ecr_two_fit <- fit_measure
```

## Bifactor Model

```{r}
model_name <- "Bifactor"
model_string <- "
Anxiety =~ ECR_1 + ECR_2 + ECR_3 + ECR_5 + ECR_7 + ECR_8
Avoidance =~ ECR_4 + ECR_6 + ECR_9 + ECR_10 + ECR_11 + ECR_12
ECR =~ ECR_1 + ECR_2 + ECR_3 + ECR_4 + ECR_5 + ECR_6 + ECR_7 + ECR_8 + ECR_9 + ECR_10 + ECR_11 + ECR_12
"
model_string
```

```{r}
cfa_fit <- cfa(
    model_string, 
    data=df,
    estimator="MLR",
    std.lv=TRUE
  )
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
ecr_bifactor_fit <- fit_measure
```

## Hierarchical

```{r}
model_name <- "Hierarchical"
model_string <- "
Anxiety =~ ECR_1 + ECR_2 + ECR_3 + ECR_5 + ECR_7 + ECR_8
Avoidance =~ ECR_4 + ECR_6 + ECR_9 + ECR_10 + ECR_11 + ECR_12
ECR =~ Anxiety + Avoidance
"
model_string
```

```{r}
cfa_fit <- cfa(
    model_string, 
    data=df,
    estimator="MLR",
    std.lv=TRUE
  )
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
ecr_hierarchical_fit <- fit_measure
```

```{r}
get_omegas(cfa_fit)
```

```{r}
sessionInfo()
```
