---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggthemes)
library(feather)
library(lubridate)
```

```{r}
df <- read_csv("../data/Compassion_14 November 2021_16.36.csv")
```
```{r}
df <- df %>% 
  slice(3:n()) %>% 
  mutate(StartDate = as.Date(StartDate)) %>% 
  filter(StartDate >= ymd("2021-01-02"))
```



```{r}
responses <- df %>% 
  select(
    ResponseId,
    starts_with("SOCS")
)

responses
```

```{r}
ordered_responses <- responses %>% 
  mutate(across(starts_with("SOCS"), ~if_else(is.na(.), ., str_extract(., "\\d$")))) %>% 
  pivot_longer(starts_with("SOCS"), names_to = "item", values_to = "response") %>% 
  mutate(response = ordered(response, levels = c("1", "2", "3", "4", "5")))

ordered_responses
```

```{r}
ordered_responses %>% 
  write_feather("../results/tidy_responses.feather")
```



```{r, fig.width=16, fig.height=9}
ggplot(ordered_responses, aes(x=response)) +
  geom_bar(stat = "count") +
  facet_wrap(~item, ncol = 10) +
  theme_few()
```

Looks like very few people fell for SOCS-O 5 (The attention check.) I'm going to remove this item and and anyone who didn't respond to it.

```{r}
filtered_responses <- responses %>% 
  mutate(across(-ResponseId, ~if_else(is.na(.), ., str_extract(., "\\d$")))) %>% 
  filter(`SOCS-O_5` == "5") %>% 
  pivot_longer(-ResponseId, names_to = "item", values_to = "response") %>% 
  mutate(response = ordered(response, levels = c("1", "2", "3", "4", "5"))) %>% 
  filter(item != "SOCS-O_5")
```

```{r, fig.width=16, fig.height=9}
ggplot(filtered_responses, aes(x=response)) +
  geom_bar(stat = "count") +
  facet_wrap(~item, ncol = 10) +
  theme_few()
```


```{r}
filtered_responses %>% 
  write_feather("../results/tidy_filtered_responses.feather")
```

```{r}
demographics <- df %>% 
  select(ResponseId, starts_with("DEM")) %>% 
  pivot_longer(-ResponseId, names_to = "dem_item", values_to = "dem_value", values_drop_na=TRUE)

demographics
```

```{r}
demographics %>% 
  write_feather("../results/tidy_demographics.feather")
```

```{r}
socs_scales <- filtered_responses %>%
  mutate(scale_type = str_extract(item, "SOCS-[A-Z]")) %>% 
  mutate(response = as.numeric(response)) %>% 
  group_by(ResponseId, scale_type) %>% 
  summarise(socs_total = sum(response)) %>% 
  pivot_wider(ResponseId, names_from = scale_type, values_from = socs_total)

socs_scales
```

```{r}
socs_scales %>% 
  write_feather("../results/socs_scales.feather")
```



```{r}
devtools::session_info()
```

