---
title: "PBIS CFAs"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(feather)
library(psych)
library(effectsize)
source("funcs.R")
```

```{r}
pbis <- read_feather("../results/tidy_pbis.feather")
```

```{r}
pbis_wide <- pbis %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  select(-ResponseId)
```

```{r, correlation}
pbis <- polychoric(pbis_wide)
```

```{r fig.asp = 0.8, fig.width = 7}
format_correlation(pbis$rho, "PBIS Polychoric")
```

```{r}
eigen(pbis$rho)$values
```

```{r}
scale_name <- "PBIS"
df <- pbis_wide
```

## One-factor model

```{r}
model_name <- "One Factor"
model_string <- "compassion =~ PBIS_1 + PBIS_2 + PBIS_3 + PBIS_4"
model_string
```

```{r}
cfa_fit <- cfa(
    model_string, 
    data=df,
    estimator="ML",
    std.lv=TRUE
  )
```

```{r}
report_fit_chi(cfa_fit)
```

```{r}
report_fit_less_chi(cfa_fit)
```

```{r}
omegas <- get_omegas(cfa_fit)
omegas
```

```{r}
omegas %>% 
  write_csv(str_c("../results/omegas/", scale_name, ".csv"))
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
pbis_one_fit <- fit_measure
```

```{r}
sessionInfo()
```
