---
title: "scale_correlations"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(feather)
library(purrr)
library(ggcorrplot)
library(viridis)
library(jtools)
library(MESS)
library(psych)
```

```{r}
all_scales <- map_dfr(Sys.glob(file.path("../results/", "*_scales.feather")), read_feather) %>% 
  pivot_longer(-ResponseId, values_drop_na = TRUE) %>% 
  pivot_wider(ResponseId)

all_scales
```

```{r}
df_cor <- cor(all_scales %>% select(-ResponseId), use="pairwise.complete.obs", method="spearman")

cor_row_names <- row.names(df_cor)

df_cor %>% 
  as_tibble() %>% 
  mutate(row_name = cor_row_names)
  # filter(str_detect(row_name, "SOCS")) %>% 
  # select(row_name, !contains("SOCS"))
```

```{r, fig.width=16/4, fig.height=9/4}
ggcorrplot(cor(all_scales %>% select(-ResponseId), use="pairwise.complete.obs", method="spearman"),
           type = "upper", hc.order = TRUE, lab=TRUE)
```

### Scale-Only adjustment

```{r}
scales <- all_scales %>% 
  select(
    `1. CEAS-SC` = CEAS_S,
    `2. Engagement Dimension 1` = CEAS_S_Engagement_Dimension_1,
    `3. Engagement Dimension 2` = CEAS_S_Engagement_Dimension_2,
    `4. Engagement` = CEAS_S_Engagement,
    `5. Action` = CEAS_S_Action,
    `6. CEAS-TO` = CEAS_TO,
    `7. Engagement` = CEAS_TO_Engagement,
    `8. Action` = CEAS_TO_Action,
    `9. CEAS-FROM` = CEAS_FROM,
    `10. Engagement` = CEAS_FROM_Engagement,
    `11. Action` = CEAS_FROM_Action,
    `12. CS` = CS_Total,
    `13. Common Humanity` = CS_Total,
    `14. Indifference (Reverse)` = CS_Total,
    `15. Kindness` = CS_Total,
    `16. Mindfulness` = CS_Total,
    `17. SOCS-S` = `SOCS-S`,
    `18. Acting or motivation to act to alleviate suffering` = SOCS_S_Acting_To_Alleviate,
    `19. Feeling suffering` = SOCS_S_Feeling_Suffering,
    `20. Recognizing Suffering` = SOCS_S_Recognizing_Suffering,
    `21. Tolerating uncomfortable feelings` = SOCS_S_Tolerating_Feelings,
    `22. Understanding the universality of suffering` = SOCS_S_Understanding_Suffering,
    `23. SOCS-O` = `SOCS-O`,
    `24. Acting or motivation to act to alleviate suffering` = SOCS_O_Acting_To_Alleviate,
    `25. Feeling suffering` = SOCS_O_Feeling_Suffering,
    `26. Recognizing Suffering` = SOCS_O_Recognizing_Suffering,
    `27. Tolerating uncomfortable feelings` = SOCS_O_Tolerating_Feelings,
    `28. Understanding the universality of suffering` = SOCS_O_Understanding_Suffering,
    `29. SCS-Positive` = Positive,
    `30. SCS-Negative` = Negative,
    `31. DASS-21` = DASS_21_Total,
    `32. ECR` = ECR_Total,
    `33. FFMQ` = FFMQ_Total,
    `34. WEMWBS` = WEMWBS
    )

cor_names <- colnames(scales)

```

```{r}
scale_cor <- corr.test(major_scales, adjust = "BH")
```

```{r}
final_results <- scale_cor$stars %>% 
  as_data_frame() %>% 
  mutate(Scale = cor_names) %>% 
  select(Scale, everything())
```

```{r}
final_results %>% 
  write_csv("../results/scale_correlation.csv")
```

### Scale-Only adjustment

```{r}
major_scales <- all_scales %>% 
  select(CEAS_FROM, CEAS_S, CEAS_TO, CS_Total, `SOCS-O`, `SOCS-S`, DASS_21_Total, ECR_Total, FFMQ_Total, SCS_Negative = Negative, SCS_Positive = Positive, WEMWBS)

major_cor_names <- colnames(major_scales)

```

```{r}
major_scale_cor <- corr.test(major_scales, adjust = "BH")
major_scale_cor
```

```{r}
major_scale_stars <- major_scale_cor$stars %>% 
  as_data_frame() %>% 
  mutate(Scale = major_cor_names) %>% 
  select(Scale, everything())
```

```{r}
major_scale_stars %>% 
  write_csv("../results/major_scale_correlation.csv")
```

### Means and Standard Deviations

```{r}
scale_means <- all_scales %>% 
  pivot_longer(-ResponseId) %>% 
  group_by(name) %>% 
  summarise(
    scale_mean = mean(value, na.rm=TRUE),
    scale_sd = sd(value, na.rm=TRUE),
    scale_min = min(value, na.rm=TRUE),
    scale_max = max(value, na.rm=TRUE)
    )
scale_means
```

```{r}
scale_means %>% 
  write_csv("../results/scale_means.csv")
```

```{r}
devtools::session_info()
```
