---
title: "SOCS-S Initial CFA"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(feather)
library(psych)
library(report)
source("funcs.R")
```

## Correlation

```{r}
df <- read_feather("../results/tidy_filtered_responses.feather") %>% 
  mutate(response = ordered(response, levels = c("1", "2", "3", "4", "5")))
```

```{r, make_df}
socs_s_df <- df %>% 
  mutate(response = as.numeric(response)) %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  select(starts_with("SOCS_S")) %>% 
  rename_with(~str_c("s", str_extract(., "\\d+"))) %>% 
  drop_na()
```

```{r, corrlation}
socs_s <- polychoric(socs_s_df)
```

```{r, fig.width=16/2, fig.height=9/2}
format_correlation(socs_s$rho, "SOCS-S Polychoric")
```

```{r}
eigen(socs_s$rho)$values
```

```{r}
scale_name <- "SOCS-S"
df <- socs_s_df
```

## One-factor model

```{r}
model_name <- "One Factor"
model_string <- str_c("compassion =~ ", str_c(colnames(df), collapse = " + "))
model_string
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
report_performance(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
fit_measure
# format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
socs_s_one_fit <- fit_measure
```

```{r}
semTools::AVE(cfa_fit) %>% kable()
```

## SOCS-S Five Factor Model

```{r}
model_name <- "Five Factor"
model_string <- '
recognizing_suffering =~ s1 + s6 + s11 + s16
universality_of_suffering =~ s2 + s7 + s12 + s17
feeling_of_suffering =~ s3 + s8 + s13 + s18
tolerating_discomfort =~ s4 + s9 + s14 + s19
alleviate_suffering =~ s5 + s10 + s15 + s20
'
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
report_performance(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
# format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
socs_s_five_fit <- fit_measure
```

```{r}
semTools::AVE(cfa_fit) %>% kable()
```

## SOCS-S Second Order Model

```{r}
model_name <- "Hierarchical"
model_string <- '
recognizing_suffering =~ s1 + s6 + s11 + s16
universality_of_suffering =~ s2 + s7 + s12 + s17
feeling_of_suffering =~ s3 + s8 + s13 + s18
tolerating_discomfort =~ s4 + s9 + s14 + s19
alleviate_suffering =~ s5 + s10 + s15 + s20
compassion =~ recognizing_suffering + universality_of_suffering + feeling_of_suffering + tolerating_discomfort + alleviate_suffering
'

```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
report_performance(cfa_fit)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
omegas <- get_omegas(cfa_fit)
omegas
```

```{r}
omegas %>% 
  write_csv(str_c("../results/omegas/", scale_name, ".csv"))
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
semTools::AVE(cfa_fit) %>% kable()
```

```{r}
socs_s_second_order_fit <- fit_measure
```

```{r}
socs_s_comparision <- bind_rows(
  socs_s_one_fit,
  socs_s_five_fit,
  socs_s_second_order_fit
)

socs_s_comparision
```

```{r}
sessionInfo()
```
