---
title: "SOCS-O Initial CFA"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(feather)
library(psych)
library(effectsize)
library(report)
source("funcs.R")
```

## Correlation

```{r}
socs <- read_feather("../results/tidy_filtered_responses.feather")
```

```{r}
socs_o_wide <- socs %>% 
  filter(str_detect(item, "SOCS_O")) %>% 
  mutate(response = as.numeric(response)) %>%
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  select(-ResponseId)
```

```{r, correlation}
socs_o <- polychoric(socs_o_wide)
```

```{r fig.asp = 0.8, fig.width = 7}
format_correlation(socs_o$rho, "SOCS-O Polychoric")
```

```{r}
eigen(socs_o$rho)$values
```

```{r}
scale_name <- "SOCS-O"
df <- socs_o_wide
```

## One-factor model

```{r}
model_name <- "One Factor"
model_string <- "compassion =~ SOCS_O_1 + SOCS_O_2 + SOCS_O_3 + SOCS_O_4 + SOCS_O_5 + SOCS_O_6 + SOCS_O_7 + SOCS_O_8 + SOCS_O_9 + SOCS_O_10 + SOCS_O_11 + SOCS_O_12 + SOCS_O_13 + SOCS_O_14 + SOCS_O_15 + SOCS_O_16 + SOCS_O_17 + SOCS_O_18 + SOCS_O_19 + SOCS_O_20"
model_string
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
report_fit_chi(cfa_fit)
```

```{r}
report_fit_less_chi(cfa_fit)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
semTools::AVE(cfa_fit) %>% kable()
```

```{r}
socs_o_one_fit <- fit_measure
```

## SOCS-O Five Factor Model

```{r}
model_name <- "Five Factor"
model_string <- '
recognizing_suffering =~ SOCS_O_1 + SOCS_O_6 + SOCS_O_11 + SOCS_O_16
universality_of_suffering =~ SOCS_O_2 + SOCS_O_7 + SOCS_O_12 + SOCS_O_17
feeling_of_suffering =~ SOCS_O_3 + SOCS_O_8 + SOCS_O_13 + SOCS_O_18
tolerating_discomfort =~ SOCS_O_4 + SOCS_O_9 + SOCS_O_14 + SOCS_O_19
alleviate_suffering =~ SOCS_O_5 + SOCS_O_10 + SOCS_O_15 + SOCS_O_20
'
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
lavInspect(cfa_fit, "cov.lv")
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
semTools::AVE(cfa_fit) %>% kable()
```

```{r}
socs_o_five_fit <- fit_measure
```

## SOCS-O Four Factor Model

```{r}
model_name <- "Four Factor"
model_string <- '
recognizing_suffering =~ SOCS_O_1 + SOCS_O_6 + SOCS_O_11 + SOCS_O_16
universality_of_suffering =~ SOCS_O_2 + SOCS_O_7 + SOCS_O_12 + SOCS_O_17
feeling_of_suffering_tolerating_discomfort =~ SOCS_O_3 + SOCS_O_8 + SOCS_O_13 + SOCS_O_18 + SOCS_O_4 + SOCS_O_9 + SOCS_O_14 + SOCS_O_19
alleviate_suffering =~ SOCS_O_5 + SOCS_O_10 + SOCS_O_15 + SOCS_O_20
'
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
report_fit_chi(cfa_fit)
```

```{r}
report_fit_less_chi(cfa_fit)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
semTools::AVE(cfa_fit) %>% kable()
```

```{r}
socs_o_four_fit <- fit_measure
```

## Hierarchical

```{r}
model_name <- "Hierarchical"
model_string <- '
recognizing_suffering =~ SOCS_O_1 + SOCS_O_6 + SOCS_O_11 + SOCS_O_16
universality_of_suffering =~ SOCS_O_2 + SOCS_O_7 + SOCS_O_12 + SOCS_O_17
feeling_of_suffering =~ SOCS_O_3 + SOCS_O_8 + SOCS_O_13 + SOCS_O_18
tolerating_discomfort =~ SOCS_O_4 + SOCS_O_9 + SOCS_O_14 + SOCS_O_19
alleviate_suffering =~ SOCS_O_5 + SOCS_O_10 + SOCS_O_15 + SOCS_O_20
compassion =~ recognizing_suffering + universality_of_suffering + feeling_of_suffering + tolerating_discomfort + alleviate_suffering
'
```

```{r}
cfa_fit <- fit_cfa(model_string, df)
```

```{r}
report_fit_chi(cfa_fit)
```

```{r}
report_fit_less_chi(cfa_fit)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
semTools::AVE(cfa_fit) %>% kable()
```

```{r}
socs_o_second_order_fit <- fit_measure
```

```{r}
socs_o_comparision <- bind_rows(
  socs_o_one_fit,
  socs_o_five_fit,
  socs_o_four_fit,
  socs_o_second_order_fit
)

format_huxtable(socs_o_comparision)
```

## Omega

```{r}
omegas <- get_omegas(cfa_fit)
omegas
```

```{r}
omegas %>% 
  write_csv(str_c("../results/omegas/", scale_name, ".csv"))
```

```{r}
sessionInfo()
```
