---
title: "SOSC-O CFAs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(feather)
library(lavaan)
library(psych)
library(broom)
library(ggthemes)
library(semTools)
library(ggcorrplot)
library(viridis)
library(blavaan)
future::plan("multisession")
library(bayesplot)
library(loo)
library(coda)
library(rstan)
options(mc.cores = 4, future.globals.maxSize=Inf)
rstan_options(auto_write = TRUE)
```

```{r}
socs <- read_feather("../results/tidy_filtered_responses.feather")
```

```{r}
socs_o_wide <- socs %>% 
  filter(str_detect(item, "SOCS_O")) %>% 
  mutate(response = as.numeric(response)) %>%
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.)))

socs_o_wide
```

```{r}
describe(socs_o_wide)
```

```{r}
socs_o_cor <- polychoric(socs_o_wide)
socs_o_cor
```

```{r}
ggcorrplot(socs_o_cor$rho, ggtheme=theme_few()) +
  scale_fill_viridis()
```

```{r}
eigen(socs_o_cor$rho)$values
```

```{r}
df <- read_feather("../results/tidy_filtered_responses.feather") %>% 
  mutate(response = ordered(response, levels = c("1", "2", "3", "4", "5")))
df
```

```{r}
socs_o_level_two_model <- '
recognizing_suffering =~ SOCS_O_1 + SOCS_O_6 + SOCS_O_11 + SOCS_O_16
universality_of_suffering =~ SOCS_O_2 + SOCS_O_7 + SOCS_O_12 + SOCS_O_17
feeling_of_suffering =~ SOCS_O_3 + SOCS_O_8 + SOCS_O_13 + SOCS_O_18
tolerating_discomfort =~ SOCS_O_4 + SOCS_O_9 + SOCS_O_14 + SOCS_O_19
alleviate_suffering =~ SOCS_O_5 + SOCS_O_10 + SOCS_O_15 + SOCS_O_20
compassion =~ recognizing_suffering + universality_of_suffering + feeling_of_suffering + tolerating_discomfort + alleviate_suffering
'
socs_o_level_two_model
```

```{r}
if (file.exists("../models/ord_socs_o_level_two_bcfa.blav")) {
  load("../models/ord_socs_o_level_two_bcfa.blav")
} else {
ord_socs_o_level_two_bcfa <- bcfa(
  socs_o_level_two_model, 
  data=socs_o_wide,
  mcmcfile = TRUE,
  save.lvs = TRUE,
  dp=dpriors(tau = "normal(0,.5)"),
  burnin = 2000,
  sample = 16000,
  n.chains = 4,
  seed = 12345,
  bcontrol = list(cores = 4),
  mcmcextra = list(monitor = c("Lambda_y_free", "Gamma_free", "B_free", "Theta_sd_free", "Theta_r_free", "Psi_sd_free", "Psi_r_mat", "Psi_r_free", "Tau_ufree", "z_aug", "ly_sign", "bet_sign", "g_sign",
 "Theta_cov", "Theta_var", "Psi_cov", "Psi_var", "Nu_free", "Alpha_free", 
 "Tau_free", "log_lik", "log_lik_sat", "ppp"))
  )
save(ord_socs_o_level_two_bcfa, file="../models/ord_socs_o_level_two_large_bcfa.blav")
}

ord_socs_o_level_two_bcfa
```

```{r}
summary(ord_socs_o_level_two_bcfa)
```

```{r}
ord_socs_o_level_two_posteriors <- blavInspect(ord_socs_o_level_two_bcfa, what="mcmc")
gelman.diag(ord_socs_o_level_two_posteriors)
```

```{r}
summary(ord_socs_o_level_two_bcfa)
```

```{r}
ord_socs_o_level_two_fit <- blavFitIndices(ord_socs_o_level_two_bcfa)
summary(ord_socs_o_level_two_fit)
```

```{r}
ord_socs_o_level_two_bcfa
```

```{r}
# stanfit
ord_socs_o_level_two_mcobj <- blavInspect(ord_socs_o_level_two_bcfa, "mcobj")
```

```{r}
ord_socs_o_level_two_loo <- rstan::loo(ord_socs_o_level_two_mcobj, moment_match=TRUE)
```

```{r}
# create a named list of draws for use with rstan methods
.rstan_relist <- function(x, skeleton) {
  out <- utils::relist(x, skeleton)
  for (i in seq_along(skeleton)) {
    dim(out[[i]]) <- dim(skeleton[[i]])
  }
  out
}

# rstan helper function to get dims of parameters right
.create_skeleton <- function(pars, dims) {
  out <- lapply(seq_along(pars), function(i) {
    len_dims <- length(dims[[i]])
    if (len_dims < 1) return(0)
    return(array(0, dim = dims[[i]]))
  })
  names(out) <- pars
  out
}

# extract original posterior draws
post_draws_stanfit <- function(x, ...) {
  as.matrix(x)
}

# compute a matrix of log-likelihood values for the ith observation
# matrix contains information about the number of MCMC chains
log_lik_i_stanfit <- function(x, i, parameter_name = "log_lik", ...) {
  loo::extract_log_lik(x, parameter_name, merge_chains = FALSE)[, , i]
}

# transform parameters to the unconstraint space
unconstrain_pars_stanfit <- function(x, pars, ...) {
  skeleton <- .create_skeleton(x@sim$pars_oi, x@par_dims[x@sim$pars_oi])
  upars <- apply(pars, 1, FUN = function(theta) {
    rstan::unconstrain_pars(x, .rstan_relist(theta, skeleton))
  })
  # for one parameter models
  if (is.null(dim(upars))) {
    dim(upars) <- c(1, length(upars))
  }
  t(upars)
}

# compute log_prob for each posterior draws on the unconstrained space
log_prob_upars_stanfit <- function(x, upars, ...) {
  apply(upars, 1, rstan::log_prob, object = x,
        adjust_transform = TRUE, gradient = FALSE)
}

# compute log_lik values based on the unconstrained parameters
log_lik_i_upars_stanfit <- function(x, upars, i, parameter_name = "log_lik",
                                  ...) {
  S <- nrow(upars)
  out <- numeric(S)
  for (s in seq_len(S)) {
    out[s] <- rstan::constrain_pars(x, upars = upars[s, ])[[parameter_name]][i]
  }
  out
}

loo::loo_moment_match.default(
  x = ord_socs_o_level_two_mcobj,
  loo = ord_socs_o_level_two_loo,
  post_draws = post_draws_stanfit,
  log_lik_i = log_lik_i_stanfit,
  unconstrain_pars = unconstrain_pars_stanfit,
  log_prob_upars = log_prob_upars_stanfit,
  log_lik_i_upars = log_lik_i_upars_stanfit
)
```

```{r}
ord_socs_o_level_two_mcobj@.MISC$stan_fit_instance$unconstrained_param_names(FALSE, FALSE)
```

```{r}
expose_stan_functions(ord_socs_o_level_two_mcobj)
```

```{r}
plot(ord_socs_o_level_two_bcfa, pars = 15:24, plot.type = "trace")
```

```{r}
pareto_k_ids(ord_socs_o_level_two_loo_fit, threshold=1)
```

```{r}
pareto_k_values(ord_socs_o_level_two_loo_fit)[214]
```

```{r}
socs_o_wide %>% 
  slice(214)
```

```{r}
loo_moment_match(blavInspect(ord_socs_o_level_two_bcfa, "mcobj"), loo=ord_socs_o_level_two_loo_fit)
```

```{r}
ord_socs_o_level_two_mcobj <- blavInspect(ord_socs_o_level_two_bcfa, "mcobj")
```

```{r}
fitmeasures(ord_socs_o_level_two_bcfa)
```

```{r}
socs_o_level_one_model <- '
recognizing_suffering =~ SOCS_O_1 + SOCS_O_6 + SOCS_O_11 + SOCS_O_16
universality_of_suffering =~ SOCS_O_2 + SOCS_O_7 + SOCS_O_12 + SOCS_O_17
feeling_of_suffering =~ SOCS_O_3 + SOCS_O_8 + SOCS_O_13 + SOCS_O_18
tolerating_discomfort =~ SOCS_O_4 + SOCS_O_9 + SOCS_O_14 + SOCS_O_19
alleviate_suffering =~ SOCS_O_5 + SOCS_O_10 + SOCS_O_15 + SOCS_O_20
'
socs_o_level_one_model
```

```{r}
if (file.exists("../models/ord_socs_o_level_one_bcfa.blav")) {
  load("../models/ord_socs_o_level_one_bcfa.blav")
} else {
ord_socs_o_level_one_bcfa <- bcfa(
  socs_o_level_one_model, 
  data=socs_o_wide,
  mcmcfile = TRUE,
  save.lvs = TRUE,
  dp=dpriors(tau = "normal(0,.5)"),
  # burnin = 2000,
  # sample = 16000,
  n.chains = 4,
  seed = 12345,
  bcontrol = list(cores = 4),
  mcmcextra = list(monitor = c("Lambda_y_free", "Gamma_free", "B_free", "Theta_sd_free", "Theta_r_free", "Psi_sd_free", "Psi_r_mat", "Psi_r_free", "Tau_ufree", "z_aug", "ly_sign", "bet_sign", "g_sign",
 "Theta_cov", "Theta_var", "Psi_cov", "Psi_var", "Nu_free", "Alpha_free", 
 "Tau_free", "log_lik", "log_lik_sat", "ppp"))
  )
save(ord_socs_o_level_one_bcfa, file="../models/ord_socs_o_level_one_bcfa.blav")
}

ord_socs_o_level_one_bcfa
```

```{r}
ord_socs_o_level_one_loo <- rstan::loo(blavInspect(ord_socs_o_level_one_bcfa, "mcobj"), moment_match=TRUE)
ord_socs_o_level_one_loo
```

```{r}
plot(ord_socs_o_level_one_bcfa, pars = 1:16, plot.type = "trace")
```

```{r}
ord_socs_o_level_one_mcmc <- blavInspect(ord_socs_o_level_one_bcfa, what = "mcmc")
gelman.diag(ord_socs_o_level_one_mcmc)
```

```{r}
gelman.plot(ord_socs_o_level_one_mcmc)
```

```{r}
geweke.plot(ord_socs_o_level_one_mcmc)
```

```{r}
ord_socs_o_level_one_fit <- blavFitIndices(ord_socs_o_level_one_bcfa)
```

```{r}
loo(blavInspect(ord_socs_o_level_one_bcfa, "mcobj"), save_psis = TRUE, moment_match = TRUE)
```

## SOCS-O

```{r}
socs_o_df <- df %>% 
  filter(str_detect(item, "SOCS-O")) %>% 
  mutate(response = as.numeric(response)) %>% 
  mutate(item_number = if_else(as.numeric(str_extract(item, "\\d+")) > 5, as.numeric(str_extract(item, "\\d+")) - 1, as.numeric(str_extract(item, "\\d+")))) %>% 
  mutate(item = str_c("o", item_number)) %>% 
  select(-item_number) %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  select(-ResponseId) %>% 
  filter_all(all_vars(!is.na(.)))
  
```

```{r}
socs_o_df %>% 
  write_feather("../results/tidy_socs_o.feather")
```

```{r}
socs_o_df
```

```{r}
socs_o <- polychoric(socs_o_df)
socs_o
```

```{r}
ggcorrplot(socs_o$rho, ggtheme=theme_few()) +
  scale_fill_viridis()
```

```{r}
eigen(socs_o$rho)$values
```

```{r}
one_factor_model <- str_c("compassion =~ ", str_c(colnames(socs_o_df), collapse = " + "))
one_factor_model
```

```{r}
one_factor_cfa <- cfa(
  one_factor_model, 
  data=socs_o_df, 
  estimator="MLR"
  )
one_factor_cfa
```

```{r}

if (file.exists("../models/one_factor_bcfa.blav")) {
  load("../models/one_factor_bcfa.blav")
} else {
one_factor_bcfa <- bcfa(
  one_factor_model, 
  data=socs_o_df,
  n.chains = 4,
  seed = 12345,
  bcontrol = list(cores = 4)
  )
save(one_factor_bcfa, file="../models/one_factor_bcfa.blav")
}

```

```{r}
blavFitIndices(one_factor_bcfa)
```

```{r}
one_loo_fit <- loo(blavInspect(one_factor_bcfa, "mcobj"), save_psis=TRUE, k_threshold = 0.5)
```

```{r}
plot(one_loo_fit, label_points = TRUE)
```

```{r}
new_one_model <- "compassion =~ o1 + o2 + o3 + o4 + o5 + o6 + o7 + o8 + o9 + o10 + o11 + o12 + o13 + o14 + o15 + o16 + o17 + o18 + o20"
```

```{r}
one_factor_bcfa <- bcfa(
  new_one_model, 
  data=socs_o_df,
  n.chains = 4,
  seed = 12345,
  bcontrol = list(cores = 4)
  )
```

```{r}
one_loo_fit <- loo(blavInspect(one_factor_bcfa, "mcobj"), save_psis=TRUE, k_threshold = 0.5)
```

```{r}
plot(one_loo_fit, label_points = TRUE)
```

```{r}
fitmeasures(one_factor_bcfa)
```

```{r}
one_factor_glance <- glance(one_factor_cfa)
one_factor_glance
```

```{r}
five_factor_model <- '
recognizing_suffering =~ o1 + o6 + o11 + o16
universality_of_suffering =~ o2 + o7 + o12 + o17
feeling_of_suffering =~ o3 + o8 + o13 + o18
tolerating_discomfort =~ o4 + o9 + o14 + o19
alleviate_suffering =~ o5 + o10 + o15 + o20
'
```

```{r}
five_factor_cfa <- cfa(
  five_factor_model, 
  data=socs_o_df, 
  estimator="MLR"
  )
five_factor_cfa
```

```{r}
summary(five_factor_cfa)
```

### Let's get Bayesian

```{r}
if (file.exists("../models/five_factor_bcfa.blav")) {
  load("../models/five_factor_bcfa.blav")
} else {
five_factor_bcfa <- bcfa(
  five_factor_model, 
  data=socs_o_df,
  n.chains = 4,
  seed = 12345,
  bcontrol = list(cores = 4)
  )
save(five_factor_bcfa, file="../models/five_factor_bcfa.blav")
}

```

```{r}
summary(five_factor_bcfa)
```

```{r}
cov2cor(blavInspect(five_factor_bcfa, "cov.lv"))
```

```{r}
omegaFromSem(five_factor_bcfa)
```

```{r}
class(five_factor_bcfa)
```

```{r}
blavInspect(five_factor_bcfa, "psrf")
```

```{r}
plot(five_factor_bcfa, 1:20, "trace")
```

```{r}
fitmeasures(five_factor_bcfa)
```

```{r}
five_loo_fit <- loo(blavInspect(five_factor_bcfa, "mcobj"), save_psis=TRUE, k_threshold = 0.5)
```

```{r}
plot(five_loo_fit, label_points = TRUE)
```

```{r}
loo_moment_match(blavInspect(five_factor_bcfa, "mcobj"), loo=five_loo_fit)
```

```{r}
cov2cor(lavInspect(five_factor_cfa, "cov.lv"))
```

```{r}
cov2cor(lavInspect(five_factor_bcfa, "cov.lv"))
```

```{r}
five_factor_pop_model <- '
recognizing_suffering =~ 1.14*o1 + 1.14*o6 + 1.14*o11 + 1.14*o16
universality_of_suffering =~ 1.14*o2 + 1.14*o7 + 1.14*o12 + 1.14*o17
feeling_of_suffering =~ 1.14*o3 + 1.14*o8 + 1.14*o13 + 1.14*o18
tolerating_discomfort =~ 1.14*o4 + 1.14*o9 + 1.14*o14 + 1.14*o19
alleviate_suffering =~ 1.14*o5 + 1.14*o10 + 1.14*o15 + 1.14*o20

recognizing_suffering ~~ 0.26*recognizing_suffering
universality_of_suffering ~~ 0.26*universality_of_suffering
feeling_of_suffering ~~ 0.26*feeling_of_suffering
tolerating_discomfort ~~ 0.26*tolerating_discomfort
alleviate_suffering ~~ 0.26*alleviate_suffering

recognizing_suffering ~~ 0.26*universality_of_suffering
recognizing_suffering ~~ 0.26*feeling_of_suffering
recognizing_suffering ~~ 0.26*tolerating_discomfort
recognizing_suffering ~~ 0.26*alleviate_suffering

universality_of_suffering ~~ 0.26*feeling_of_suffering
universality_of_suffering ~~ 0.26*tolerating_discomfort
universality_of_suffering ~~ 0.26*alleviate_suffering

feeling_of_suffering ~~ 0.26*tolerating_discomfort
feeling_of_suffering ~~ 0.26*alleviate_suffering

tolerating_discomfort ~~ 0.26*alleviate_suffering
'

```

```{r}
five_factor_pa <- SSpower(five_factor_model, popModel = five_factor_pop_model, n=10, alpha=0.2, nparam=0, std.lv=TRUE)
```

```{r}
five_factor_pa
```

```{r}
eigen(lavInspect(five_factor_cfa, "cov.lv"))
```

```{r}
lavInspect(five_factor_cfa, "cov.lv")
```

```{r}
inspect(five_factor_cfa, what="std")$lambda
```

```{r}
five_factor_glance <- glance(five_factor_cfa)
five_factor_glance
```

```{r}
hierarchical_factor_model <- '
recognizing_suffering =~ o1 + o6 + o11 + o16
universality_of_suffering =~ o2 + o7 + o12 + o17
feeling_of_suffering =~ o3 + o8 + o13 + o18
tolerating_discomfort =~ o4 + o9 + o14 + o19
alleviate_suffering =~ o5 + o10 + o15 + o20
compassion =~ recognizing_suffering + universality_of_suffering + feeling_of_suffering + tolerating_discomfort + alleviate_suffering
'
hierarchical_factor_model
```

```{r}
hierarchical_factor_cfa <- cfa(
  hierarchical_factor_model, 
  data=socs_o_df, 
  estimator="MLR"
  )
hierarchical_factor_cfa
```

```{r}
if (file.exists("../models/hierarchical_factor_bcfa.blav")) {
  load("../models/hierarchical_factor_bcfa.blav")
} else {
hierarchical_factor_bcfa <- bcfa(
  hierarchical_factor_model,
  inits = "simple",
  data=socs_o_df,
  n.chains = 4,
  seed = 12345,
  bcontrol = list(cores = 4)
  )
save(hierarchical_factor_bcfa, file="../models/hierarchical_factor_bcfa.blav")
}
```

```{r}
as.data.frame(hierarchical_factor_bcfa@ParTable)
```

```{r}
dpriors()
```

```{r}
blavInspect(hierarchical_factor_bcfa, "inits")
```

```{r}
hierarchical_fit <- blavFitIndices(hierarchical_factor_bcfa)
```

```{r, fig.width=16/2, fig.height=9/2}
plot(hierarchical_factor_bcfa,1:20, plot.type = "trace")
```

```{r}
dpriors(hierarchical_factor_bcfa)
```

```{r}
bcfa_compare <- blavCompare(one_factor_bcfa, hierarchical_factor_bcfa)
```

```{r}
bcfa_compare
```

```{r}
hierarchical_loo_fit <- loo(blavInspect(hierarchical_factor_bcfa, "mcobj"), save_psis = TRUE, k_threshold = 0.5)
```

```{r}
plot(hierarchical_loo_fit, label_points = TRUE)
```

```{r}
loo_moment_match(blavInspect(hierarchical_factor_bcfa, "mcobj"), hierarchical_loo_fit)
```

```{r}
plot(hierarchical_loo_fit)
```

```{r}
pareto_k_ids(hierarchical_loo_fit)
```

```{r}
summary(hierarchical_loo_fit)
```

```{r}
hierarchical_loo_mm_fit <- loo(blavInspect(hierarchical_factor_bcfa, "mcobj"), moment_match = TRUE)
```

### Model improvements

```{r}
new_factor_model <- '
recognizing_suffering =~ o1 + o6 + o11 + o16
universality_of_suffering =~ o2 + o7 + o12 + o17
feeling_of_suffering =~ o3 + o8 + o13 + o18 + o4 + o9 + o14 
alleviate_suffering =~ o5 + o10 + o15 + o20
'
```

```{r}
new_factor_bcfa <- bcfa(
  new_factor_model, 
  data=socs_o_df,
  n.chains = 4,
  seed = 12345,
  bcontrol = list(cores = 4)
  )
```

```{r}
new_factor_bcfa
```

```{r}
sessionInfo()
```
