---
title: "PBIS CFAs"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(feather)
library(psych)
library(effectsize)
source("funcs.R")
```

```{r}
wemwbs <- read_feather("../results/tidy_wemwbs.feather")
```

```{r}
wemwbs_wide <- wemwbs %>% 
  pivot_wider(values_from = response, id_cols = ResponseId, names_from = item) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  select(-ResponseId)
```

```{r, correlation}
wemwbs <- polychoric(wemwbs_wide)
```

```{r fig.asp = 0.8, fig.width = 7}
format_correlation(wemwbs$rho, "WEMWBS Polychoric")
```

```{r}
eigen(wemwbs$rho)$values
```

```{r}
scale_name <- "WEMWBS"
df <- wemwbs_wide
```

## One-factor model

```{r}
model_name <- "One Factor"
model_string <- "WEMWBS =~ WEMWBS_1 + WEMWBS_2 + WEMWBS_3 + WEMWBS_4 + WEMWBS_5 + WEMWBS_6 + WEMWBS_7 + WEMWBS_8 + WEMWBS_9 + WEMWBS_10 + WEMWBS_11 + WEMWBS_12 + WEMWBS_13 + WEMWBS_14"
model_string
```

```{r}
cfa_fit <- cfa(
    model_string, 
    data=df,
    estimator="MLR",
    std.lv=TRUE
  )
```

```{r}
get_omegas(cfa_fit)
```

```{r}
interpret_fit(cfa_fit)
```

```{r}
fit_measure <- lav_fit_measures(cfa_fit, df, scale_name, model_name)
format_huxtable(fit_measure)
```

```{r}
format_sem_paths(cfa_fit, scale_name, model_name)
```

```{r}
format_huxtable(format_cfa_parameters(cfa_fit))
```

```{r}
wemwbs_one_fit <- fit_measure
```

```{r}
sessionInfo()
```
